import { Card, CardContent } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Map, RotateCcw, Share, Printer } from "lucide-react";
import { MarkdownRenderer } from "@/components/ui/markdown";

interface ItineraryDisplayProps {
  itinerary: string | null;
  isGenerating: boolean;
  onRegenerate: () => void;
}

export default function ItineraryDisplay({ itinerary, isGenerating, onRegenerate }: ItineraryDisplayProps) {
  const handleShare = () => {
    if (navigator.share && itinerary) {
      navigator.share({
        title: "My Travel Itinerary",
        text: itinerary,
      });
    } else {
      // Fallback to copying to clipboard
      navigator.clipboard.writeText(itinerary || "");
    }
  };

  const handlePrint = () => {
    window.print();
  };

  if (!itinerary && !isGenerating) {
    return (
      <Card className="h-fit">
        <CardContent className="p-6">
          <div className="text-center py-12">
            <div className="w-16 h-16 bg-gray-100 rounded-full flex items-center justify-center mx-auto mb-4">
              <Map className="w-8 h-8 text-gray-400" />
            </div>
            <h3 className="text-lg font-medium text-gray-900 mb-2">Your Itinerary Will Appear Here</h3>
            <p className="text-gray-500">Fill out the form on the left to generate your personalized travel plan.</p>
          </div>
        </CardContent>
      </Card>
    );
  }

  return (
    <Card className="h-fit">
      <CardContent className="p-6">
        {itinerary && (
          <>
            <div className="flex items-center justify-between mb-6">
              <div>
                <h3 className="text-xl font-semibold text-gray-900">Your Travel Itinerary</h3>
                <p className="text-gray-600 text-sm">Generated by Globe Trotter AI</p>
              </div>
              <div className="flex space-x-2">
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={onRegenerate}
                  className="p-2"
                  title="Regenerate"
                >
                  <RotateCcw className="w-4 h-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handleShare}
                  className="p-2"
                  title="Share"
                >
                  <Share className="w-4 h-4" />
                </Button>
                <Button
                  variant="ghost"
                  size="sm"
                  onClick={handlePrint}
                  className="p-2"
                  title="Print"
                >
                  <Printer className="w-4 h-4" />
                </Button>
              </div>
            </div>

            <div className="prose prose-sm max-w-none">
              <MarkdownRenderer content={itinerary} />
            </div>

            <div className="mt-8 p-4 bg-gray-50 rounded-lg">
              <div className="flex items-center space-x-2 text-sm text-gray-600">
                <Map className="w-4 h-4" />
                <span>Generated by Globe Trotter AI • Customize your itinerary as needed</span>
              </div>
            </div>
          </>
        )}
      </CardContent>
    </Card>
  );
}
